// Generated by scripts/gen-screen-routes.mjs — do not edit.
// To add or change a screen, edit src/screens/registry.ts and run `pnpm gen:routes`.
import { connection } from 'next/server';
import Screen from '@/screens/crm/broadcast';

export default async function Page() {
  // Rendered for each request, never frozen at build time.
  await connection();
  return <Screen />;
}
