// Generated by scripts/gen-screen-routes.mjs — do not edit.
// To add or change a screen, edit src/screens/registry.ts and run `pnpm gen:routes`.
import { connection } from 'next/server';
import Screen from '@/screens/reach/reports';

export default async function Page({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  // Rendered for each request, never frozen at build time.
  await connection();
  return <Screen searchParams={searchParams} />;
}
